raw:
  record:
    output-file: raw_records.data
twitter:
  consumerKey: ${TWITTER_API_KEY}
  consumerSecret: ${TWITTER_API_SECRET_KEY}
  accessToken: ${TWITTER_ACCESS_TOKEN}
  accessTokenSecret: ${TWITTER_TOKEN_SECRET}
  collector:
    requested-page-size: 300
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:cultural}
      username: ${MONGO_USER:-root}
      password: ${MONGO_PASS:-secret}
      authentication-database: admin
