- name: Deploy Cultural service
  hosts: all
  gather_facts: yes
  vars:
    timestamp: "{{ ansible_date_time.epoch }}"
  tasks:
    - name: Deployment block
      block:
        - name: Create deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: directory

        - name: Copy compose file
          copy:
            src: ../docker-compose.yml
            dest: ~/deploy-{{ timestamp }}/docker-compose.yml

        - name: Start up database
          docker_compose:
            project_src: ~/deploy-{{ timestamp }}
            project_name: cultural_footprint
            services: mongo
            state: present

        - name: Start up application
          docker_compose:
            project_src: ~/deploy-{{ timestamp }}
            project_name: cultural_footprint
            services: cultural
            state: present
            pull: yes
            restarted: true
          environment:
            TWITTER_API_KEY: "{{ lookup('env', 'TWITTER_API_KEY') }}"
            TWITTER_API_SECRET_KEY:  "{{ lookup('env', 'TWITTER_API_SECRET_KEY') }}"
            TWITTER_ACCESS_TOKEN: "{{ lookup('env', 'TWITTER_ACCESS_TOKEN') }}"
            TWITTER_TOKEN_SECRET:  "{{ lookup('env', 'TWITTER_TOKEN_SECRET') }}"
            TELEGRAM_BOT_TOKEN:  "{{ lookup('env', 'TELEGRAM_BOT_TOKEN') }}"
            TELEGRAM_BOT_USERNAME:  "{{ lookup('env', 'TELEGRAM_BOT_USERNAME') }}"

      always:
        - name: Remove deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: absent
