name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker login docker.pkg.github.com -u sausageRoll -p ${GITHUB_TOKEN} && docker build . --file Dockerfile --tag cultural_footprint:latest
    - name: Publish the Docker image
      run: docker push docker.pkg.github.com/sausageRoll/cultural-footprint/cultural_footprint:latest
