name: Deployment

on: [ push ]
#   push:
#     branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create inventory file
      run: echo ${{ secrets.InstanceIp }} > ./deployment/hosts

    - name: Execute Ansible Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: ./deployment/deploy.yaml
        inventoryFile: ./deployment/hosts
        extraVars: "ansible_user=deployer ansible_password=${{ secrets.InstancePassword }}"
